name: Apply to Main repo
on:
  push:
    branches: [main]
jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3 python3-pip
          pip3 install ww2ogg revorb
      
      - name: Clone and update repo
        run: |
          git clone https://github.com/NowhereArchive/NowhereAudios2.git
          cd NowhereAudios2
          
          # Convert WEM to OGG to AAC
          find . -name "*.wem" -type f | while read wem_file; do
            echo "Processing: $wem_file"
            
            # Get the base filename without extension
            base_name="${wem_file%.wem}"
            ogg_file="${base_name}.ogg"
            aac_file="${base_name}.aac"
            
            # WEM to OGG (using ww2ogg)
            ww2ogg "$wem_file" -o "$ogg_file" --pcb packed_codebooks_aoTuV_603.bin || {
              echo "Failed to convert $wem_file to OGG, trying alternative method..."
              # Fallback: try direct ffmpeg conversion
              ffmpeg -i "$wem_file" -acodec libvorbis "$ogg_file" -y || continue
            }
            
            # OGG to AAC (using ffmpeg)
            if [ -f "$ogg_file" ]; then
              ffmpeg -i "$ogg_file" -c:a aac -b:a 192k "$aac_file" -y
              
              # Clean up intermediate files
              if [ -f "$aac_file" ]; then
                rm "$wem_file" "$ogg_file"
                echo "✅ Converted: $aac_file"
              fi
            fi
          done
          
          # Commit and push changes
          git config user.name "NowhereArchive"
          git config user.email "178385478+NowhereArchive@users.noreply.github.com"
          git add .
          git commit -m "Convert WEM to AAC" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/NowhereArchive/NowhereAudios2.git HEAD:main