name: Apply to Main repo
on:
  push:
    branches: [main]

jobs:
  push_changes:
    runs-on: windows-latest
    steps:
      - name: Checkout (with vgmstream-cli.exe in your repo)
        uses: actions/checkout@v4

      - name: Clone and update repo
        shell: pwsh
        run: |
          git clone https://github.com/NowhereArchive/NowhereAudios3.git
          cd NowhereAudios3
          Copy-Item ../* -Recurse -Force -Exclude ".git", ".github", "NowhereAudios3"
          
          git config user.name "NowhereArchive"
          git config user.email "178385478+NowhereArchive@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/NowhereArchive/NowhereAudios3.git
          git add .
          git commit -m "Updates" || echo "No changes to commit"
          git push -u origin main
