name: Audios

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone repos
        shell: pwsh
        run: |
          git clone https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/NowhereArchive/NowhereAudios2.git
          git clone https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/NowhereArchive/NowhereAudios.git

      - name: Make changes to NowhereAudios
        shell: pwsh
        run: |
          rm -r -force NowhereAudios\audio
          md NowhereAudios\audio
          Get-ChildItem -Path NowhereAudios2\* -Recurse -Dir | ForEach-Object {
              if ($_.FullName -notlike "*.git*") {
                cp -r -force $_.FullName .\NowhereAudios\audio
              }
          }

      - name: Push files to NowhereAudios
        shell: pwsh
        run: |
          cd NowhereAudios
          git config user.name "NowhereArchive"
          git config user.email "178385478+NowhereArchive@users.noreply.github.com"
          
          git add .
          
          $status = git status --porcelain
          if ($status) {
              git commit -m "Updates"
              git push origin main
          } else {
              Write-Host "No changes to commit"
          }